### ISSUE TITLE
Blank results with Facebook Module.

### ISSUE THREAD

**Issue by Inf3r** [SpiderLabs/social_mapper#101]
First of all, sorry for my horrible english and my congratulations to the creator for this wonderful tool (GreenWolf). I wanted to tell about a problem that I had for a long time and that I was finally able to solve. Facebook could not interpret the tool for language reasons (it was in Spanish) so when it was translated into english it started to work perfectly. On the other hand I want to suggest that in the examples we define the correct version of python2.7 (which in the readme is python) and brings confusion. The problem I had was not working therefore it was very difficult to solve for my little experience. In the searches -fb the program responded with good login and expired the session with blank results. Anyway, any language other than English that has these symptoms here is the solution. Greetings from Argentina.

**Comment by Green-Wolf** [comment]
Hi @Inf3r! Greetings from the United Kingdom! Thank you very much for your kind words. I think we have a little bit of a language barrier, but from what i understand theres a problem with the facebook module when the account being used is from a non english speaking country? 

Could you please provide some screenshots (Running with -s mode to show the browser), console output or talk a bit more about the issue to help me understand? You could also submit a pull request with your changes so i can have a look over them and look into merging them into the code base. I'll add you to the contributors page if so 😃

**Comment by Inf3r** [comment]
Hey @Green-Wolf! Thank you for the quick reply, i promise that as soon as my son sleeps I show you what happens with a video. Sorry Alain for my poor explanation.

**Comment by Inf3r** [comment]
Pd: The option to show the browser doesn't work for me...by the way all works fine!

**Comment by Inf3r** [comment]
![socialm1](https://user-images.githubusercontent.com/47500805/52544068-28396700-2d8d-11e9-9d1c-a7951a0fd96f.png)
![socialm2](https://user-images.githubusercontent.com/47500805/52544069-28d1fd80-2d8d-11e9-8ad3-6eb963e03ef0.png)

**Comment by Green-Wolf** [comment]
Oh i see, thats a good point. Is that the account your logging into which is set to english/spanish, or the target account?

If it's the account you're using to log into, maybe i should just update the readme to let people know to put their accounts into english while running the tool?

**Comment by Inf3r** [comment]
That is the point or directly focus on the design of the tool so that when parsing the text strings these are not only in english.

**Comment by Inf3r** [comment]
P.d: Sorry i forget your question...the account i'm using to log its my account...

**Comment by Green-Wolf** [comment]
For the time being i've updated the readme to include an additional setup step to put the facebook account into english. 

Thank you very much for bringing this to my attention, i'm sure it will help other users who are having difficulties. I'm going to close this for now as we have a workaround. However feel free to submit a pull request to make the code work with both English and Spanish if you are able to do so.

**Comment by Inf3r** [comment]
No problem! :)
I will do everything i can to implement this to the tool!
