### ISSUE TITLE
Can I do it in an environment called Windows Subsystem for Linux?

### ISSUE THREAD

**Issue by Opp0** [SpiderLabs/social_mapper#102]
My environment is Windows, but recently Ubuntu dedicated to Windows has been updated so I am using it. Can I use Social Mapper in that environment?

**Comment by VasyaTheWizard** [comment]
I don't see why it wouldn't. Installing packages from APT works just like in regular Ubuntu, so you could just install the requirements and run it. Give it a try!

**Comment by Opp0** [comment]
understood. Also, although I was able to do "Prerequisites 3" now, I do not know what to do from 4
[.https://github.com/SpiderLabs/social_mapper/blob/726071510c060896bb7c4d77d3feb01a0deecc73/social_mapper.py#L30-L61 ](url)
where you can enter the username and password exactly as you specified?

**Comment by VasyaTheWizard** [comment]
Open social_mapper.py with a text editor, there's global variables at the top of the file where you can enter the credentials.
