### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by Opp0** [SpiderLabs/social_mapper#103]
When I try to vim and edit social_mapper, it will be displayed as follows. What is this error?

E325: ATTENTION
Found a swap file by the name ".social_mapper.py.swp"
          owned by: ubuntu   dated: Sun Mar  3 15:47:37 2019
         file name: ~ubuntu/Users/social_mapper/social_mapper.py
          modified: YES
         user name: ubuntu   host name: DESKTOP-VIIK5T2
        process ID: 3014 (still running)
While opening file "social_mapper.py"
             dated: Sun Mar  3 16:00:10 2019
      NEWER than swap file!

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r social_mapper.py"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file ".social_mapper.py.swp"
    to avoid this message.

**Comment by Green-Wolf** [comment]
I'm not sure what this is, perhaps something to do with the windows/linux subsystem you are using. Try just opening the file in notepad if your wanting to enter in your credentials.
