### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by Opp0** [SpiderLabs/social_mapper#104]
I entered this. Error is happened. What should I do? ("myhome" is a folder that contains pictures.)
python social_mapper.py -f imagefolder -i /lan/social_mapper/myhome -m fast
-fb
＞Traceback (most recent call last):
File "social_mapper.py", line 931, in 
for filename in os.listdir(args.input):
OSError: [Errno 2] No such file or directory: '/lan/social_mapper/myhome/'

**Comment by Green-Wolf** [comment]
Probally another issue with windows subsystem for linux, try making a little python test file and see if you can open and print a file in '/lan/social_mapper/myhome/'? Could be something to do with linux being / and windows being C:\
