### ISSUE TITLE
Always uses LinkedIn

### ISSUE THREAD

**Issue by gjchester** [SpiderLabs/social_mapper#106]
Hi

Saw this at BlackHat (Great Demo!!) but only just got around to trying it.

Cloned and Installed yesterday so its V 0.1.0 but should have all the latest fixes.
Running on Ubuntu 18..04.2 x64   Geckodriver is V0.22.0

All set up (I have a Selenium error but thats not the problem here)  and I have my accounts for FB/IG/TW/G+/LI entered in.   I *can log in to all of them bar Twitter which keeps asking me to enter a code that its not actually sending to the phone but again different issue.

If I specify a service, then no matter way it tried to use Linked in.

As an example 

python social_mapper.py -f company -i "Microsoft" -m fast -fb

it then proceeds to fetch 25 linked in results, 

LI is the first set of creds so it could be barfing on the next (FB) creds, but copy any pasting them out of the social_mapper.py in to a web browser lets me log on to FB ok

Any Suggestions, I didn't see anything similar in the issues, but may have missed it.?

![image](https://user-images.githubusercontent.com/6544336/54025935-04065580-4194-11e9-82a3-34c63f664164.png)

![image](https://user-images.githubusercontent.com/6544336/54025951-141e3500-4194-11e9-9523-c927f296da10.png)

**Comment by Cvrew** [comment]
Hey, it's not a solution to the problem, would you give me advice to solve my problem?https://github.com/SpiderLabs/social_mapper/issues/105

**Comment by Greenwolf** [comment]
Hi @gjchester, thank you for your kind words on my blackhat demo. Was it the Vegas or London one? 

So the reason it’s looking up on LinkedIn is that is how it gets an initial target list if you tell it to go after a company. It does a LinkedIn reverse search by people attached to the company on LinkedIn. 

After it has finished on LinkedIn it will do your Facebook search. Alternatively you can provide it with a csv with url links to images, or a folder with images that you have gathered manually.

**Comment by gjchester** [comment]
It as at London, pity the booths were so close to gether as it was hard to concentrate on just one talk. as the sound bled over.

Anyway thanks, You may wish to consider it saying why it does that as it may confuse others too.

**Comment by Cvrew** [comment]
Is that so. How many programming languages do you know? I also want to know when and how I learned.
I am currently learning python with a book.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by sowhat82** [comment]
> Hi @gjchester, thank you for your kind words on my blackhat demo. Was that the Vegas or London one?
> 
> So the reason it’s looking up on LinkedIn is that is how it gets an initial target list if you tell it to go after a company. It does a LinkedIn reverse search by people attached to the company on LinkedIn.
> 
> After it has finished on LinkedIn it will do your Facebook search. Alternatively you can provide it with a csv with url links to images, or a folder with images that you have gathered manually.
> 
> Does this solve your problem?

Hi Greenwolf,

Great program by the way. However, I'm facing a similar issue. Doing a company search only gives me hits on linkedin, even though I specify -fb as well.

Also, using the imagefolder or csv methods don't seem to return any results, even when I use the "default" Bill Gates data.

Any idea why?

Thanks
