### ISSUE TITLE
ImportError: No module named html.entities

### ISSUE THREAD

**Issue by Greenaxio** [SpiderLabs/social_mapper#11]
```
Traceback (most recent call last):
  File "social_mapper.py", line 3, in <module>
    import facebookfinder
  File "./modules\facebookfinder.py", line 8, in <module>
    from bs4 import BeautifulSoup
  File "C:\Python27\lib\site-packages\bs4\__init__.py", line 36, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "C:\Python27\lib\site-packages\bs4\builder\__init__.py", line 7, in <module>
    from bs4.element import (
  File "C:\Python27\lib\site-packages\bs4\element.py", line 13, in <module>
    from bs4.dammit import EntitySubstitution
  File "C:\Python27\lib\site-packages\bs4\dammit.py", line 14, in <module>
    from html.entities import codepoint2name
ImportError: No module named html.entities
```

**Comment by cclauss** [comment]
See the note at the top of https://docs.python.org/2.7/library/htmllib.html  For some strange reason bs4 is looking for the Python 3 name instead of the Python 2 name.

**Comment by Ewpratten** [comment]
try `python -m pip install --upgrade --no-cache-dir beautifulsoup4`

**Comment by Greenaxio** [comment]
@Ewpratten is said that it's already up to date

**Comment by cclauss** [comment]
try __python2 -m pip install --upgrade --no-cache-dir beautifulsoup4__  # With the __2__ on the end of python

**Comment by Greenaxio** [comment]
@cclauss I am using py for python 2. I did run it with that. So all fine there

**Comment by cclauss** [comment]
So can this issue be close or not?

**Comment by Greenaxio** [comment]
No, it still does not work. I meant to say I already tried what you said. Sorry for the misunderstanding

**Comment by Greenaxio** [comment]
1: `Python 2.7.15`
2: `py2 not found`
3: `ImportError: No module named html.entities`
6: `4.6.1`
7: ``

The Error disappeared!

Now there are others errors but I'll close this Issue

**Comment by cclauss** [comment]
Nice...  For future reference, the __py__ syntax is __py -2__ or __py -3__
