### ISSUE TITLE
Error Filling out Facebook Profiles

### ISSUE THREAD

**Issue by hoxflank** [SpiderLabs/social_mapper#13]
python social_mapper.py -f imagefolder -i ~/Downloads/pic -m fast -fb

[-] Error Filling out Facebook Profiles [-]
Message: Process unexpectedly closed with status 1

[-]

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:01.350334

**Comment by jjfneto** [comment]
Hello, there is an identical question to yours.

**Comment by jjfneto** [comment]
I recommend closing your question and focusing only on one.

https://github.com/SpiderLabs/social_mapper/issues/5

**Comment by hoxflank** [comment]
Closing. See #5

**Comment by hoxflank** [comment]
Thanks, not sure how i missed that. I closed mine.

Joe Stracner
This e-mail was powered by Google Apps.
