### ISSUE TITLE
django.utils problem

### ISSUE THREAD

**Issue by gggomg** [SpiderLabs/social_mapper#18]
Good day, guys. Thank you for your work and soft, but I need help with this

Traceback (most recent call last):
File "social_mapper.py", line 27, in <module>
import encoding
ImportError: No module named encoding`

I've already insalled django.utils

**Comment by Green-Wolf** [comment]
Did you install it using the requirements.txt file?

**Comment by gggomg** [comment]
Nope, just pip-install

**Comment by Green-Wolf** [comment]
So you did 'pip install django'?

**Comment by gggomg** [comment]
Python 2.7.15

**Comment by Green-Wolf** [comment]
Closing this and removing the reference in the readme to windows, this was never tested, just presumed based on python. My apologies. Please run on OSX, Linux or a Linux VM. Let me know if you run into any issues on these platforms and i'll be happy to help.

**Comment by gggomg** [comment]
Thank you, I will try.
