### ISSUE TITLE
[-] Error Filling out Facebook Profiles [-] Message: connection refused

### ISSUE THREAD

**Issue by jarinlima** [SpiderLabs/social_mapper#19]
Hey!! Excellent job, but i don't understand a problem, it's always says : 

[-] Error Filling out Facebook Profiles [-]
Message: connection refused

What are the reasons for connection refused?

**Comment by Greenaxio** [comment]
There already is an Issue for that, I think. But I don't know how 'good' it is.
[Issue #5](https://github.com/SpiderLabs/social_mapper/issues/5)

**Comment by ajhong2** [comment]
I'm having similar issues with connection refused. I was able to get past Issue 5 by installing xvfb, but connection refused seems to be a different problem.

**Comment by Green-Wolf** [comment]
Is this still an issue? Other people seem be connecting ok. What OS/version are you using? Could you try finding out which line the error is coming from to help narrow it down?

**Comment by Snorkeldink** [comment]
**This is most likely due to a geckodriver version mismatch issue.** 
If you are using geckodriver 0.21.0 then you need : 

- Firefox 57 (and greater)
- Selenium 3.11 (and greater)

See https://github.com/mozilla/geckodriver/releases

If you are using some debian based distro (kali linux?) which uses firefox-esr , you need tu upgrade to firefox quantum. You could also try an older version of geckodriver which will work with firefox-esr.

**Comment by ajhong2** [comment]
Hmm, I seem to be having different issues now. I am on Kali Linux and removed firefox-esr. Installed Firefox Quantum (61.0.2).  Now I get the following error:

`[-] Error Filling out Facebook Profiles [-]
Message: Unable to find a matching set of capabilities`

**Comment by Snorkeldink** [comment]
That's a different issue not relevant here ... use this python script below for testing (change the path of geckodriver to where you put it).

If all works, it should open your latest firefox on seleniumhq website.

```
from selenium import webdriver

browser = webdriver.Firefox(executable_path='/usr/bin/geckodriver')
browser.get('http://seleniumhq.org/')
```

**Comment by jjfneto** [comment]
A possible solution...

https://github.com/SpiderLabs/social_mapper/issues/5#issuecomment-412663941

**Comment by Green-Wolf** [comment]
Closing as it seems to be an issue with not using the correct versions of Geckodriver. Thank you for your help @Snorkeldink, much appreciated

**Comment by Blackperl337** [comment]
> 
> 
> **This is most likely due to a geckodriver version mismatch issue.**
> If you are using geckodriver 0.21.0 then you need :
> 
>     * Firefox 57 (and greater)
> 
>     * Selenium 3.11 (and greater)
> 
> 
> See https://github.com/mozilla/geckodriver/releases
> 
> If you are using some debian based distro (kali linux?) which uses firefox-esr , you need tu upgrade to firefox quantum. You could also try an older version of geckodriver which will work with firefox-esr.

This is the exact solution. I tried this and it works as expected. Thanks..
