### ISSUE TITLE
Can't run, ImportError

### ISSUE THREAD

**Issue by tshanib** [SpiderLabs/social_mapper#2]
It's not running, gives these lines  

File "social_mapper.py", line 1, in <module>
    from modules import facebookfinder
ImportError: No module named modules

**Comment by jebrcidea** [comment]
Not the cleanest, but change all that has modules for this
import sys
sys.path.insert(0, './modules')
import facebookfinder
import twitterfinder
import instagramfinder
import linkedinfinder
import vkontaktefinder
import weibofinder
import doubanfinder
import googleplusfinder
 And it will compile

Also, it's missing facebook-sdk. So you know, pip install facebook-sdk

**Comment by tshanib** [comment]
Thank you, It works

**Comment by TheDuchy** [comment]
or add __init__.py into the modules directory....

**Comment by cclauss** [comment]
Does this also work?

```python
import modules.facebookfinder
import modules.twitterfinder
import modules.instagramfinder
import modules.linkedinfinder
import modules.vkontaktefinder
import modules.weibofinder
import modules.doubanfinder
import modules.googleplusfinder
```

**Comment by TheDuchy** [comment]
you will still need the \_\_init\_\_.py file, but yes

**Comment by xannaxX** [comment]
TheDuchy where is that file  __init__.py?

**Comment by xannaxX** [comment]
python social_mapper.py 
  File "social_mapper.py", line 111
    print "Facebook Check %i/%i : %s" % (count,ammount,person.full_name)
                                    ^
SyntaxError: invalid syntax

**Comment by Ewpratten** [comment]
@xannaxX are you using python 2.7 ?

**Comment by xannaxX** [comment]
Ewpratten  both 2.7 and 3.6 i guess

**Comment by xannaxX** [comment]
python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux

**Comment by xannaxX** [comment]
python2.7 social_mapper.py 
Traceback (most recent call last):
  File "social_mapper.py", line 1, in <module>
    from modules import facebookfinder
ImportError: No module named modules
  but  i did import it all  as you can see 
ls
docs              linkedinfinder          social_mapper.py
doubanfinder      modules                 sys
googleplusfinder  modules.facebookfinder  twitterfinder
Input-Examples    README.md               vkontaktefinder
instagramfinder   setup                   weibofinder
 any help please :)

**Comment by cclauss** [comment]
from .modules import facebookfinder  # Add the dot (.)

**Comment by xannaxX** [comment]
yes now it works .  thx

**Comment by cclauss** [comment]
So can this issue be close or not?

**Comment by xannaxX** [comment]
yes for me :) thank you

**Comment by auduongxuan** [comment]
@xannaxX Does it works? do you have error like this
[https://photos.google.com/album/AF1QipOwsAur9K95hmiVIoX7b342IcDfTvoeLRp4-W7c/photo/AF1QipO_E7Miqd_7MkF9tHsfsvgFjL9gDI4dDqCpyFpA](url)

**Comment by ThallesCanela** [comment]
$ python2.7 social_mapper.py -f company -i "SpiderLabs" -m accurate -a -t strict
Traceback (most recent call last):
  File "social_mapper.py", line 13, in <module>
    import facebook
ImportError: No module named facebook


Note: The problem is not with the classes of the folder "modules", but with the classes that are in the folder "social_mapper /". Does anyone have a solution?

**Comment by Z3r0Sh3ll** [comment]
hey guys i have problem still .. not working ...

error :

`Traceback (most recent call last):
  File "social_mapper.py", line 2, in <module>
    from modules import facebookfinder
  File "/root/social_mapper/modules/facebookfinder.py", line 4, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'
`
this command : 
`pip install PyVirtualDisplay
`
i have it output : 

`Requirement already satisfied: PyVirtualDisplay in /usr/local/lib/python2.7/dist-packages (0.2.1)
Requirement already satisfied: EasyProcess in /usr/local/lib/python2.7/dist-packages (from PyVirtualDisplay) (0.2.7)
`

**Comment by cclauss** [comment]
__python3 -m pip install -r setup/requirements.txt__

**Comment by Z3r0Sh3ll** [comment]
> @xannaxX Does it works? do you have error like this
> https://photos.app.goo.gl/xW93KG66RNGtTUNQA

Hi thanks ...


`python3 -m pip install -r setup/requirements.t`

output:

`Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from -r setup/requirements.txt (line 1)) (4.7.1)
Requirement already satisfied: selenium in /usr/local/lib/python3.7/dist-packages (from -r setup/requirements.txt (line 2)) (3.141.0)
Collecting pyvirtualdisplay (from -r setup/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/cf/ad/b15f252bfb0f1693ad3150b55a44a674f3cba711cacdbb9ae2f03f143d19/PyVirtualDisplay-0.2.4-py2.py3-none-any.whl
Requirement already satisfied: tabulate in /usr/lib/python3/dist-packages (from -r setup/requirements.txt (line 4)) (0.8.2)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r setup/requirements.txt (line 5)) (2.21.0)
Collecting face_recognition (from -r setup/requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/3f/ed/ad9a28042f373d4633fc8b49109b623597d6f193d3bbbef7780a5ee8eef2/face_recognition-1.2.3-py2.py3-none-any.whl
Collecting django (from -r setup/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/d6/57/66997ca6ef17d2d0f0ebcd860bc6778095ffee04077ca8985928175da358/Django-2.2.4-py3-none-any.whl
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from -r setup/requirements.txt (line 8)) (1.16.2)
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from -r setup/requirements.txt (line 9)) (1.2.2)
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from -r setup/requirements.txt (line 10)) (3.0.2)
Collecting scikit-image (from -r setup/requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/2e/21/ea56c8bb2e8112837dd71aebeb2ac67913e784911c0d7f493a593fa1a207/scikit_image-0.15.0-cp37-cp37m-manylinux1_x86_64.whl
Collecting scikit-learn (from -r setup/requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/9f/c5/e5267eb84994e9a92a2c6a6ee768514f255d036f3c8378acfa694e9f2c99/scikit_learn-0.21.3-cp37-cp37m-manylinux1_x86_64.whl
Requirement already satisfied: ipython in /usr/lib/python3/dist-packages (from -r setup/requirements.txt (line 13)) (5.8.0)
Collecting dlib (from -r setup/requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/05/57/e8a8caa3c89a27f80bc78da39c423e2553f482a3705adc619176a3a24b36/dlib-19.17.0.tar.gz
Collecting facebook-sdk (from -r setup/requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/79/d7/4cb0f5930f79205cc45db22e17fa716396d813c3d6b8d5de77783a5fa59a/facebook_sdk-3.1.0-py2.py3-none-any.whl
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from selenium->-r setup/requirements.txt (line 2)) (1.24.1)
Collecting EasyProcess (from pyvirtualdisplay->-r setup/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/fa/29/40040d1d64a224a5e44df9572794a66494618ffe5c77199214aeceedb8a7/EasyProcess-0.2.7-py2.py3-none-any.whl
Requirement already satisfied: Click>=6.0 in /usr/lib/python3/dist-packages (from face_recognition->-r setup/requirements.txt (line 6)) (7.0)
Collecting face-recognition-models>=0.3.0 (from face_recognition->-r setup/requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/cf/3b/4fd8c534f6c0d1b80ce0973d01331525538045084c73c153ee6df20224cf/face_recognition_models-0.3.0.tar.gz
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from face_recognition->-r setup/requirements.txt (line 6)) (6.1.0)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from django->-r setup/requirements.txt (line 7)) (2019.1)
Collecting sqlparse (from django->-r setup/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl
Collecting PyWavelets>=0.4.0 (from scikit-image->-r setup/requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/e3/91/607449f27a3a068739498eddf921cf2686f0a71fa8b44a8efce0af9446a8/PyWavelets-1.0.3-cp37-cp37m-manylinux1_x86_64.whl
Collecting imageio>=2.0.1 (from scikit-image->-r setup/requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/af/0a/943c965d372dae0b1f1482677d29030ab834351a61a9a632fd62f27f1523/imageio-2.5.0-py3-none-any.whl
Collecting networkx>=2.0 (from scikit-image->-r setup/requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/85/08/f20aef11d4c343b557e5de6b9548761811eb16e438cee3d32b1c66c8566b/networkx-2.3.zip
Collecting joblib>=0.11 (from scikit-learn->-r setup/requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/cd/c1/50a758e8247561e58cb87305b1e90b171b8c767b15b12a1734001f41d356/joblib-0.13.2-py2.py3-none-any.whl
Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages (from ipython->-r setup/requirements.txt (line 13)) (4.6.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/lib/python3/dist-packages (from networkx>=2.0->scikit-image->-r setup/requirements.txt (line 11)) (4.3.0)
Building wheels for collected packages: dlib, face-recognition-models, networkx
  Running setup.py bdist_wheel for dlib ... done
  Stored in directory: /root/.cache/pip/wheels/50/b6/b5/5f46aacfd18028ff57591cfb53fcc7554362977c15e9060e67
  Running setup.py bdist_wheel for face-recognition-models ... done
  Stored in directory: /root/.cache/pip/wheels/d2/99/18/59c6c8f01e39810415c0e63f5bede7d83dfb0ffc039865465f
  Running setup.py bdist_wheel for networkx ... done
  Stored in directory: /root/.cache/pip/wheels/de/63/64/3699be2a9d0ccdb37c7f16329acf3863fd76eda58c39c737af
Successfully built dlib face-recognition-models networkx
Installing collected packages: EasyProcess, pyvirtualdisplay, face-recognition-models, dlib, face-recognition, sqlparse, django, PyWavelets, imageio, networkx, scikit-image, joblib, scikit-learn, facebook-sdk
Successfully installed EasyProcess-0.2.7 PyWavelets-1.0.3 django-2.2.4 dlib-19.17.0 face-recognition-1.2.3 face-recognition-models-0.3.0 facebook-sdk-3.1.0 imageio-2.5.0 joblib-0.13.2 networkx-2.3 pyvirtualdisplay-0.2.4 scikit-image-0.15.0 scikit-learn-0.21.3 sqlparse-0.3.0
`

`python3 social_mapper.py`

`Traceback (most recent call last):
  File "social_mapper.py", line 9, in <module>
    from modules import googlelusfinder
ImportError: cannot import name 'googlelusfinder' from 'modules' (/root/social_mapper/modules/__init__.py)`

**Comment by Z3r0Sh3ll** [comment]
I had to remove two lines of code that I had added myself and I think I had no reason to modulate those two lines of code.

from modules import googleplusfinder
from modules import pyvirtualdisplay

**Comment by Z3r0Sh3ll** [comment]
with remove that ....it will be work ofcourse with thanks of @cclauss  thank you so much
