### ISSUE TITLE
NameError: name 'argparse' is not defined

### ISSUE THREAD

**Issue by auduongxuan** [SpiderLabs/social_mapper#21]
I imported those text to "social_mapper.py"
"import sys
sys.path.insert(0, './modules')
import facebookfinder
import twitterfinder
import instagramfinder
import linkedinfinder
import vkontaktefinder
import weibofinder
import doubanfinder
import googleplusfinder"

and create a empty file "__init__.py" in modules.
But the error appear:

# python2.7 social_mapper.py
Traceback (most recent call last):
  File "social_mapper.py", line 829, in <module>
    parser = argparse.ArgumentParser(
NameError: name 'argparse' is not defined

Help me please!

**Comment by Ewpratten** [comment]
Have you imported argparse?

**Comment by auduongxuan** [comment]
@Ewpratten thanks, I imported argparse but I have another problem as image below
https://photos.app.goo.gl/TmyEASxGfbwY3QTU9

**Comment by Ewpratten** [comment]
no idea. I dont touch facebook.. someone else was having this problem too..
