### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by zidan9873** [SpiderLabs/social_mapper#23]
I try to write python social_mapper.py -f GOOGLE -i "Company Name Here" -m accurate -a -t strict and I get an error:
python: can't open file 'social_mapper.py': [Errno 2] No such file or directory

**Comment by Greenaxio** [comment]
You are probably in the wrong directory withing the console

**Comment by zidan9873** [comment]
I am in ~/social_mapper/setup
Where is the correct directory?

**Comment by Greenaxio** [comment]
~/social-mapper

you need to back out of the setup dir

**Comment by zidan9873** [comment]
I still get the same error
Do you can upload a video of examples?
