### ISSUE TITLE
AttributeError: 'module' object has no attribute 'lru_cache'

### ISSUE THREAD

**Issue by Greenaxio** [SpiderLabs/social_mapper#26]
```
Traceback (most recent call last):
  File "social_mapper.py", line 35, in <module>
    from django.utils import encoding
  File "C:\Python27\lib\site-packages\django\__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "C:\Python27\lib\site-packages\django\utils\version.py", line 71, in <module>
    @functools.lru_cache()
AttributeError: 'module' object has no attribute 'lru_cache'
```

**Comment by Green-Wolf** [comment]
Is that the full stack trace? Do you get it with a specific set of targets or all the time?

**Comment by Greenaxio** [comment]
That's the whole output, for all targets.

**Comment by Green-Wolf** [comment]
Closing this and removing the reference in the readme to windows, this was never tested, just presumed based on python. My apologies but even if we fix this current issue you will run into other issues later on. Please run on OSX, Linux or a Linux VM.

**Comment by Greenaxio** [comment]
Fixed the Error by redownloading everything and installing django manually with 

`python2 -m pip install Django==1.11.15`
