### ISSUE TITLE
Google option -gp

### ISSUE THREAD

**Issue by scrimpys** [SpiderLabs/social_mapper#27]
Getting this error when using -gp - other services are ok 

[+] Google Login Page Part 1 loaded successfully [+]
[+] Google Login Page Part 2 loaded successfully [+]
[+] Google Login Page Part 3 loaded successfully [+]
Traceback (most recent call last):
  File "social_mapper.py", line 1127, in <module>
    peoplelist = fill_googleplus(peoplelist)
  File "social_mapper.py", line 466, in fill_googleplus
    GooglePlusfinderObject.doLogin(google_username,google_password)
  File "./modules/googleplusfinder.py", line 49, in doLogin
    gpPassword.send_keys(password)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <div class="Xb9hP"> is not reachable by keyboard

**Comment by Green-Wolf** [comment]
Google could have made a change here, seems to be failing on the send password, will have to look at this later.

**Comment by Green-Wolf** [comment]
I havn't seen any other people having issues with Google Plus so i'm chalking this down to a selenium issue thats probably been resolved.

**Comment by Soutcast** [comment]
I have the exact same issue when trying to run it on mac

**Comment by Soutcast** [comment]
Found out that this is not an issue with the selenium install it is an issue with the googleplusfinder.py code as when entering the password it tries to enter the password into the password div rather than the password input. Changes to code are posted below:
`gpPassword = self.driver.find_element_by_class_name("Xb9hP") gpPassword.send_keys(password)`

to

`gpPassword = self.driver.find_element_by_class_name("whsOnd.zHQkBf") gpPassword.send_keys(password)`

**Comment by Soutcast** [comment]
hope this helps

**Comment by Green-Wolf** [comment]
Hi @Soutcast, thanks for this, i appreciate you taking the time to help with these issues, however i'm running it now and not having a problem with the current code?

**Comment by Soutcast** [comment]
Hi @Green-Wolf, I am unsure why it is that only certain people experience this issue and I will try to figure it out. If anyone experiences an issue like this just reference this solution because it helped me when I experienced this problem.
