### ISSUE TITLE
cmd=['Xvfb', '-help'] The system cannot find the file specified

### ISSUE THREAD

**Issue by brandostrong** [SpiderLabs/social_mapper#28]
[-] Error Filling out Facebook Profiles [-]
cmd=['Xvfb', '-help']
OSError=[Error 2] The system cannot find the file specified
Program install error!
[-]

Windows 10

**Comment by scrimpys** [comment]
I had this on my Mac OS install.  Xvfb (X virtual framebuffer).  I had to install XQuartz which is the Apple X11 implementation.  Try using/installing pyvirtualdisplay. Not done it myself given I don't run Windows.

**Comment by ThallesCanela** [comment]
I saved all the procedures I used to correct the problems that were encountered during compilation attempts.
There remained only 2 problems (# 29).
Hope this helps!
==================================== PT-BR ====================================
Eu salvei todos os procedimentos que eu utilizei para corrigir os problemas que iam surgindo drante as tentativas de compilação.
Permaneceram apenas 2 problemas (#29).
Espero ter ajudado!
Link:
[http://ec2-18-219-141-101.us-east-2.compute.amazonaws.com/nextcloud/index.php/s/YQxpzBjBj8DEyfG](url)

**Comment by Snorkeldink** [comment]
I don't think it's possible to run Xvfb on windows ...

**Comment by Green-Wolf** [comment]
Has anyone managed to have it work on Windows yet? It was only theoretically supposed to work on windows as it's python. I've only tested on OSX and Linux.

**Comment by SamehEtaiwi** [comment]
I still have this issue ... I'm also running Windows 10

**Comment by Snorkeldink** [comment]
There is no implementation of PyVirtualDisplay xvfb on windows. You cannot run xvfb on windows. You just can't. You need to use something else than xfvb or use linux/os to run this.

As for linux obviously you also need to install xvfb. Not with PIP but with apt-get or whatever you use. The error message is quite clear.

**Comment by Green-Wolf** [comment]
Closing this and removing the reference in the readme to windows, this was never tested, just presumed based on python. Please run on OSX, Linux or a Linux VM.

**Comment by JX-Wang** [comment]
My py program have this issue too, But my environment is win10 in Pycharm,  Maybe it  wont work in Windows OS?
