### ISSUE TITLE
face_recognition hash problem

### ISSUE THREAD

**Issue by PiratKV** [SpiderLabs/social_mapper#31]
![screenshot_1](https://user-images.githubusercontent.com/42313459/44000136-1bf12ee6-9e23-11e8-90a1-9a420d05995f.jpg)
![screenshot_2](https://user-images.githubusercontent.com/42313459/44000137-1ff5100c-9e23-11e8-81d8-b3eacd6b1994.jpg)

**Comment by Green-Wolf** [comment]
Try uninstalling and reinstalling the face_recognition package
pip uninstall face_recognition

Otherwise reopen and let me know what OS this is on?

**Comment by Green-Wolf** [comment]
Support for Windows 10 was dropped as it was lacking certain requirements to get working, please use Mac or Linux.
