### ISSUE TITLE
'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

### ISSUE THREAD

**Issue by xF4t3** [SpiderLabs/social_mapper#32]
I attempted to run command below:
`python social_mapper.py -f imagefolder -i Input-Examples/imagefolder -m fast -fb`
But I got an error:
`[-] Error Filling out Facebook Profiles [-]
'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
[-]`
This ran with `-tw` argument
How can I fix it?

**Comment by Green-Wolf** [comment]
I've come across this before, i must be a string that needs to be stripped with the django function that i've missed. It will be tricky to identify without knowing the name that you're feeding in/profiles its extracting. Are you about to find the line which is a problem yourself and left me know?

**Comment by simullacra** [comment]
I'm having the exact issue as well. 
`python social_mapper.py -f imagefolder -i ./imagefolder  -m fast -fb -s

[-] Error Filling out Facebook Profiles [-]
'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)
[-]
`
Same applies to `-vk ` option 
```
python social_mapper.py -f imagefolder -i /usr/local/social_mapper/imagefolder  -m fast -vk -s
Traceback (most recent call last):
  File "social_mapper.py", line 1132, in <module>
    peoplelist = fill_vkontakte(peoplelist)
  File "social_mapper.py", line 546, in fill_vkontakte
    VkontaktefinderObject.doLogin(vk_username,vk_password)
  File "/usr/local/social_mapper/modules/vkontaktefinder.py", line 29, in doLogin
    if(str(self.driver.title).encode('ascii','replace').startswith("Log in")):
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```

**Comment by Green-Wolf** [comment]
Changes look good, thanks for the effort you've put into this @TADT1909
