### ISSUE TITLE
empty result

### ISSUE THREAD

**Issue by k4v1c5** [SpiderLabs/social_mapper#34]
Hi, my problem is the following:

Kali Linux, Firefox 61.0.2, Selenium 3.11

_python ~/gladio/social_mapper/social_mapper.py -f imagefolder -i ~/gladio/social_mapper/mytargets -m fast -fb

[+] Facebook Login Page loaded successfully [+]
[+] Facebook Login Success [+]

Facebook Check 1/1 : Bill Gates                                

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:16.855816_

AND 

the result file is empty.
_results-social-mapper.csv
Full Name,Facebook
"Bill Gates",""_

**Comment by lostrapt** [comment]
I get empty results if I don't fill any of the social media credentials.
If I do I get an error:

`Traceback (most recent call last):
  File "social_mapper.py", line 1115, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "social_mapper.py", line 221, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "/Users/.../social_mapper-master/modules/twitterfinder.py", line 14, in __init__
    display = Display(visible=0, size=(1600, 1024))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error! `

**Comment by LBraccoPutta** [comment]
@lostrapt , did you install xvfb via apt-get ?

@k4v1c5 , same here. I run `python social_mapper.py -f imagefolder -i ./Input-Examples/imagefolder/ -m fast -tw`

Result : 

[+] Twitter Login Page loaded successfully [+]
[-] Twitter Login Failed [-]

Twitter Check 4/4 : Linus Torvalds                                

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:34.76644

Checked csv file `cat results-social-mapper.csv`  & csv file is empty : 

Full Name,Twitter
"Steve Jobs",""
"Bill Gates",""
"pOMVq1xtMM0",""
"Linus Torvalds",""

**Using** :
Mozilla Firefox 61.0.2
geckodriver 0.21.0
selenium 3.14.0

**Comment by Green-Wolf** [comment]
Try using the '-s' option to see if the login is working correctly, or if the browser is starting/navigating to twitter. Let me know where the flaw is occurring so we can troubleshoot this.

**Comment by Green-Wolf** [comment]
I'm sorry but i don't have any experience debugging geckodriver output. If the selenium test works, and you don't get any errors on the command line it should be fine. Has anyone else managed to get in running on Kali? 

All I can think of based off your original post is to try running it from the social mapper folder as it could be a problem with the initial image paths?
$ python social_mapper.py -f imagefolder -i ./mytargets -m fast -fb

**Comment by cloudsoh** [comment]
-s doesn't open the Firefox in Ubuntu, is there any prerequisite?
Also it doesn't return me any result, with no errors.
Also I couldn't login Facebook with correct credential.

**Comment by Green-Wolf** [comment]
Selenium by default should show the browser, if you use the -s option it won't auto hide it. So there a problem with your geckodriver/selenium/firefox installations. Try doing a fresh firefox install with the latest geckodriver and selenium. If these don't work i would recommend using Kali and it's been verified as working with the current steps on Kali + OSX.

**Comment by Green-Wolf** [comment]
Closing as the steps for getting social mapper to work on Kali have been added to the readme. Please open another issue for Ubuntu if the steps above don't work.
