### ISSUE TITLE
Setup.py issues!

### ISSUE THREAD

**Issue by ramramtau** [SpiderLabs/social_mapper#35]
Collecting face_recognition
  Downloading https://files.pythonhosted.org/packages/28/10/f153bbbc218fc169768aa1c02f2e9178e9241e4af8da56289bdca2c0c217/face_recognition-1.2.2-py2.py3-none-any.whl
Requirement already satisfied: numpy in c:\python27\lib\site-packages (from face_recognition) (1.15.0)
Requirement already satisfied: Click>=6.0 in c:\python27\lib\site-packages (from face_recognition) (6.7)
Requirement already satisfied: face-recognition-models>=0.3.0 in c:\python27\lib\site-packages (from face_recognition) (0.3.0)
Collecting dlib>=19.7 (from face_recognition)
  Downloading https://files.pythonhosted.org/packages/df/aa/6a9bb2a763107bb2606d6ee1aa65fcd3b51375a9ef6436e9c9280b0dd63c/dlib-19.15.0.tar.gz (3.3MB)
    100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 3.3MB 3.7MB/s
Requirement already satisfied: Pillow in c:\python27\lib\site-packages (from face_recognition) (5.2.0)
Installing collected packages: dlib, face-recognition
  Running setup.py install for dlib ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\skynet\\appdata\\local\\temp\\pip-install-xxibv7\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\skynet\appdata\local\temp\pip-record-92wkr5\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
    Invoking CMake setup: 'cmake c:\users\skynet\appdata\local\temp\pip-install-xxibv7\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=c:\users\skynet\appdata\local\temp\pip-install-xxibv7\dlib\build\lib.win-amd64-2.7 -DPYTHON_EXECUTABLE=c:\python27\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=c:\users\skynet\appdata\local\temp\pip-install-xxibv7\dlib\build\lib.win-amd64-2.7 -A x64'
    -- Building for: Visual Studio 14 2015
    -- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.10240.
    -- The C compiler identification is unknown
    -- The CXX compiler identification is unknown
    CMake Error in CMakeLists.txt:
      No CMAKE_C_COMPILER could be found.

    CMake Error in CMakeLists.txt:
      No CMAKE_CXX_COMPILER could be found.

    -- Configuring incomplete, errors occurred!
    See also "C:/Users/SkyNet/AppData/Local/Temp/pip-install-xxibv7/dlib/build/temp.win-amd64-2.7/Release/CMakeFiles/CMakeOutput.log".
    See also "C:/Users/SkyNet/AppData/Local/Temp/pip-install-xxibv7/dlib/build/temp.win-amd64-2.7/Release/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\skynet\appdata\local\temp\pip-install-xxibv7\dlib\setup.py", line 257, in <module>
        'Topic :: Software Development',
      File "c:\python27\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python27\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\skynet\appdata\local\temp\pip-install-xxibv7\dlib\setup.py", line 133, in run
        self.build_extension(ext)
      File "c:\users\skynet\appdata\local\temp\pip-install-xxibv7\dlib\setup.py", line 170, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "c:\python27\lib\subprocess.py", line 190, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'c:\\users\\skynet\\appdata\\local\\temp\\pip-install-xxibv7\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=c:\\users\\skynet\\appdata\\local\\temp\\pip-install-xxibv7\\dlib\\build\\lib.win-amd64-2.7', '-DPYTHON_EXECUTABLE=c:\\python27\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=c:\\users\\skynet\\appdata\\local\\temp\\pip-install-xxibv7\\dlib\\build\\lib.win-amd64-2.7', '-A', 'x64']' returned non-zero exit status 1

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\skynet\\appdata\\local\\temp\\pip-install-xxibv7\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\skynet\appdata\local\temp\pip-record-92wkr5\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\skynet\appdata\local\temp\pip-install-xxibv7\dlib\

**Comment by Green-Wolf** [comment]
Closing this and removing the reference in the readme to windows, this was never tested, just presumed based on python. My apologies. Please run on OSX, Linux or a Linux VM.
