### ISSUE TITLE
Facebook session has expired attempting to reestablish...

### ISSUE THREAD

**Issue by jdgualteros** [SpiderLabs/social_mapper#36]
python social_mapper.py -f imagefolder -i ./Input-Examples/imagefolder/ -m fast -fb

[+] Facebook Login Page loaded successfully [+]
[+] Facebook Login Success [+]

Facebook Check 1/1 : xxxxx                               
Facebook session has expired attempting to reestablish...
Facebook Timeout Error, session has expired and attempts to reestablish have failed

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:01:52.266670

**Comment by Green-Wolf** [comment]
This usually occurs when the internet connection is a bit spotty, can you try running from a different location or connection to test?

**Comment by FahadAkash** [comment]
i have also same problem i try to different conncetion but same error plzz help me how to fix it

**Comment by Greenwolf** [comment]
Hi @FahadAkash, you need a faster internet connection i believe. You could try hosting in the cloud if your connection is spotty.
