### ISSUE TITLE
Login fails + LinkedIn reached error page

### ISSUE THREAD

**Issue by orblatt** [SpiderLabs/social_mapper#37]
For some reason, Twitter, Instagram and LinkedIn raises "Login Failed" although credentials are valid:
"
Instagram Check 1/2 : xxxxxxxxxxxx
[+] Instagram Login Page loaded successfully [+]
[-] Instagram Login Failed [-]

Instagram Timeout Error, session has expired and attempts to reestablish have failed
"

Also, another error is raised while connecting to LinkedIn:"

selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=https%3A//www.linkedin.com/uas/login&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20www.linkedin.com.

**Comment by LBraccoPutta** [comment]
@orblatt , for Twitter add **not Login nickname** - add what goes after @ sign. 

For example : Your nickname was orblatt. But what goes after @ sign is orblatt1. So, add orblatt1 into social_mapper.py file.

**Comment by orblatt** [comment]
The first problem is solved, although the second one with LinkedIn still shows up..
