### ISSUE TITLE
something went wrong!!!!

### ISSUE THREAD

**Issue by kx2000xx** [SpiderLabs/social_mapper#40]
i used the imagefolder example in tool files but it's gives me an error and searching stopped 

`root@kali:~/Desktop/social_mapper# python social_mapper.py -f imagefolder -i /root/Desktop/social_mapper/Input-Examples/imagefolder/ -m fast -fb -tw
Please provide Facebook Login Credentials in the social_mapper.py file
Please provide Twitter Login Credentials in the social_mapper.py file`

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: `0:00:00.001946`

the errors are:

`Please provide Facebook Login Credentials in the social_mapper.py file`
`Please provide Twitter Login Credentials in the social_mapper.py file`

what can i do for this ??

**Comment by efdutra** [comment]
You need to have a valid account on those sites to try to search.

open social_mapper.py and fill the blanks "" with user and passwords for the social media accounts
