### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by efdutra** [SpiderLabs/social_mapper#41]
I do have all of the required tools installed and Ok on my Kali distro.
but when i try to run a FACEBOOK only search
i get this:

```
root@kali:~/social_mapper# python social_mapper.py -f csv -i /root/social_mapper/csv.csv -m accurate -fb
[-] Error Filling out Facebook Profiles [-]
Message: Unable to find a matching set of capabilities

[-]


Results file: SM-Results/-root-social_mapper-csv.csv-social-mapper.csv
HTML file: SM-Results/-root-social_mapper-csv.csv-social-mapper.html

Image folder: SM-Results/-root-social_mapper-csv.csv-social-mapper

Task Duration: 0:00:02.156552
root@kali:~/social_mapper#
```

If i try any other social media, this happens:

```
root@kali:~/social_mapper# python social_mapper.py -f csv -i /root/social_mapper/csv.csv -m accurate -ig
Traceback (most recent call last):
  File "social_mapper.py", line 1116, in <module>
    peoplelist = fill_instagram(peoplelist)
  File "social_mapper.py", line 295, in fill_instagram
    InstagramfinderObject = instagramfinder.Instagramfinder(showbrowser)
  File "/root/social_mapper/modules/instagramfinder.py", line 19, in __init__
    self.driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 167, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

```

Can anyone help me ?

**Comment by DannyMatar** [comment]
Try using this fix  #19 . By Snorkeldink:

That's a different issue not relevant here ... use this python script below for testing (change the path of geckodriver to where you put it).

If all works, it should open your latest firefox on seleniumhq website.

```
from selenium import webdriver

browser = webdriver.Firefox(executable_path='/usr/bin/geckodriver')
browser.get('http://seleniumhq.org/')

```

**Comment by LBraccoPutta** [comment]
@efdutra , download latest version of geckodriver for latest firefox or correct one for your "old" firefox.

**Comment by efdutra** [comment]
@LBraccoPutta im using lastest version of both

**Comment by Soutcast** [comment]
I have the same issue as @efdutra and the code that @DannyMatar posted does not work for me. Does that mean it is an issue with the Selenium install?

**Comment by Soutcast** [comment]
I am using Kali Linux 2017 with the default Firefox-ESR installed. I have the latest version of geckodriver.

**Comment by Soutcast** [comment]
I have also installed all of the requirements and there were no errors that I know of.

**Comment by Green-Wolf** [comment]
Hi @Soutcast, yes i'm afraid if the code that @DannyMatar does not work for you the problem is with your selenium install. I believe someone posted in another issue that Firefox-ESR on kali needs an older compatible version of geckodriver. Have a look back through the issues and look online for guides on how to get selenium working on your OS/version

**Comment by Soutcast** [comment]
@Green-Wolf what OS do you use as I might use your OS if you have social mapper working without errors.

**Comment by efdutra** [comment]
@Green-Wolf im not using Firefox-ESR, i've updated it to the latest and removed the ESR version.
Algo i got the geckodriver driver latest too.

The code that @DannyMatar posted, also didn't worked for me.

Im still stuck on this, BUT it only happens on my Kali (also using the latest).

I've tryied on my Mac Sierra, did work just fine (needed to install some other tools, but worked well)

**Comment by Soutcast** [comment]
@efdutra what extra tools did you install to get it working? As I have been unable to get it working on mac.

**Comment by Green-Wolf** [comment]
@Soutcast I'm using OSX to run it like @efdutra. I would also be interested in which other tools you installed?

**Comment by Green-Wolf** [comment]
Would be great if anyone using Kali could share what steps they used to get it working/if you ran into problems/if it worked smoothly

**Comment by Soutcast** [comment]
@Green-Wolf @efdutra, Do you know if this is just Kali specific or an error experienced on all Linux versions. Has anyone got it working on Linux versions other than Kali?

**Comment by efdutra** [comment]
@Soutcast i installed https://www.xquartz.org on my Mac.

**Comment by Green-Wolf** [comment]
Seems to be resolved, thanks to everyone for feeding back the steps you took. I've updated the Readme.md and mac install instructions to reflect the need to install a more up to date version of Firefox on Kali, and xquartz and xcode on Mac.
