### ISSUE TITLE
Letter with accent are just ignored

### ISSUE THREAD

**Issue by N1nj4Turtl3** [SpiderLabs/social_mapper#44]
Hello,
When there is accent on letter in the name these letters are just skipped, see below:

```
root@ubuntu:~/social_mapper$ ll img/
total 240
drwxrwxrwx 2 root root   4096 aug  17 17:50  ./
drwxrwxr-x 9 root root   4096 aug  17 17:53  ../
-rwxrwxrwx 1 root root 235817 aug  17 17:38 'Úrsula Corberó.jpg'*
```

```
root@ubuntu:~/social_mapper$ python social_mapper.py -f imagefolder -i img/ -m accurate -t loose -s -fb -ig

[+] Facebook Login Page loaded successfully [+]
[+] Facebook Login Success [+]

Facebook Check 1/1 : rsula Corber                                
[+] Instagram Login Page loaded successfully [+]
[+] Instagram Login Success [+]

Instagram Check 1/1 : rsula Corber

rsula Corber
	Facebook: https://www.facebook.com/toquio.corbero.75?ref=br_rs
	Instagram: https://instagram.com/ursulolita_fanpage/


Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:02:07.099920
```

```
root@ubuntu:~/social_mapper$ cat SM-Results/results-social-mapper.csv
Full Name,Facebook,Instagram
"rsula Corber","https://www.facebook.com/toquio.corbero.75?ref=br_rs","https://instagram.com/ursulolita_fanpage/"
```

Would it be possible to add the support of all letter with accent?
It could be related to a lack of support regarding the used encoding?
This will help in some case, and will participate to have accurate results, like on fb for example.

Great job by the way!

**Comment by Green-Wolf** [comment]
Hi @N1nj4Turtl3, thanks very much for flagging this. Yes in development there were problems converting between string types from different sites & selenium. So in the end i just stripped out anything that wasn't ascii. Not a very elegant solution, and one i hope to fix one day, time permitting. If anyone in the community wants to get involved that would be fantastic!

**Comment by Green-Wolf** [comment]
If anyone wants to look into this before i get to it, the issue is whenever i've used the django library encoding.smart_str function.
