### ISSUE TITLE
no module named modules 

### ISSUE THREAD

**Issue by bdharris0113** [SpiderLabs/social_mapper#45]
when running this , I return the following error

```
Traceback (most recent call last):
  File "social_mapper.py", line 1, in <module>
    from modules import facebookfinder
ImportError: No module named modules
```

**Comment by Green-Wolf** [comment]
Do you have the latest version with the __init__.py file in the modules directory? Are you running:
$ python social_mapper.py x x x
from the social_mapper folder?
