### ISSUE TITLE
Suggestion: Add some automated testing like Travis CI, Circle CI, Appveyor

### ISSUE THREAD

**Issue by cclauss** [SpiderLabs/social_mapper#47]
They are all free for Open Source projects like this one.

https://github.com/marketplace/category/continuous-integration

Pick one and I will help you to get it working.  It will help the transition to Python 3.

**Comment by cclauss** [comment]
All three work the same way...
1. You add a file to the root of your repo:
    * .travis.yml
    * .circleci/config.yml
    * .appveyor.yml
2. You log into their website with your GitHub id and turn the repo ON.

The next time a PR or code change is submitted, the system will git clone your repo and tests will run.  Nothing to install locally.

**Comment by cclauss** [comment]
Tell me which of the three services you want and I will give you the yml file.

**Comment by Green-Wolf** [comment]
I honestly have no experience with any of them, do you have a recommendation? Also thanks for all your help recently @cclauss, it's much appreciated. 🥇

**Comment by cclauss** [comment]
@Green-Wolf Some of the second pass flake8 issues might be worth looking at.  https://travis-ci.org/SpiderLabs/social_mapper/jobs/418896492#L2144

Especially C901,E722,F401  Many of the others are just about _style_ and could be automatically fixed by passing the code through black, autopep8, or yapf.

**Comment by Green-Wolf** [comment]
Thanks i'll have a look, will have to learn this on the fly 😄
