### ISSUE TITLE
ASCII codec can't encode characters.

### ISSUE THREAD

**Issue by KVM1L** [SpiderLabs/social_mapper#48]
I installed the tool and all it's requirements, but when i run this command:

`python2 social_mapper.py -f imagefolder -i ./h -m fast -fb`

, i'm getting this error:

```
[-] Error Filling out Facebook Profiles [-]
'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)
[-]
```

Any solution?

**Comment by TADT1909** [comment]
This issue is duplicated to #32 
And I fixed it yesterday, with pull requests #46 
@KVM1L, you should update your source code.
