### ISSUE TITLE
Mac Install Error

### ISSUE THREAD

**Issue by Soutcast** [SpiderLabs/social_mapper#49]
Whenever I try to install the requirements on mac I get these two errors:

`pywavelets 0.5.2 has requirement numpy>=1.9.1, but you'll have numpy 1.8.0rc1 which is incompatible.
scikit-image 0.14.0 has requirement matplotlib>=2.0.0, but you'll have matplotlib 1.3.1 which is incompatible.
scikit-image 0.14.0 has requirement scipy>=0.17.0, but you'll have scipy 0.13.0b1 which is incompatible.`

And

`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-zy7TWd/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-AOyhPh/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-zy7TWd/dlib/`

This seems to be similar to #35 
Any Ideas?

**Comment by Soutcast** [comment]
Entire code output here:

`Requirement already satisfied: beautifulsoup4 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1)) (4.6.3)
Requirement already satisfied: selenium in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2)) (3.14.0)
Requirement already satisfied: pyvirtualdisplay in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3)) (0.2.1)
Requirement already satisfied: tabulate in /Library/Python/2.7/site-packages (from -r requirements.txt (line 4)) (0.8.2)
Requirement already satisfied: requests in /Library/Python/2.7/site-packages (from -r requirements.txt (line 5)) (2.19.1)
Collecting face_recognition (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/28/10/f153bbbc218fc169768aa1c02f2e9178e9241e4af8da56289bdca2c0c217/face_recognition-1.2.2-py2.py3-none-any.whl
Collecting django (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/f8/1c/31112c778b7a56ce18e3fff5e8915719fbe1cd3476c1eef557dddacfac8b/Django-1.11.15-py2.py3-none-any.whl (6.9MB)
    100% |████████████████████████████████| 7.0MB 4.4MB/s 
Requirement already satisfied: numpy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from -r requirements.txt (line 8)) (1.8.0rc1)
Requirement already satisfied: scipy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from -r requirements.txt (line 9)) (0.13.0b1)
Requirement already satisfied: matplotlib in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from -r requirements.txt (line 10)) (1.3.1)
Collecting scikit-image (from -r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/14/6c/67d8aeeeae8cb0a6117bcaee35ccead489e085859b404d3cf2c37066ec78/scikit_image-0.14.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (29.0MB)
    100% |████████████████████████████████| 29.1MB 7.4MB/s 
Collecting scikit-learn (from -r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/22/47/dfc1c815a75afc940789df0e125d55cf9e1eceaf589d89f285f9df575235/scikit_learn-0.19.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (7.6MB)
    100% |████████████████████████████████| 7.6MB 7.9MB/s 
Collecting ipython (from -r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/b0/88/d996ab8be22cea1eaa18baee3678a11265e18cf09974728d683c51102148/ipython-5.8.0-py2-none-any.whl (760kB)
    100% |████████████████████████████████| 768kB 6.1MB/s 
Collecting dlib (from -r requirements.txt (line 14))
  Downloading https://files.pythonhosted.org/packages/df/aa/6a9bb2a763107bb2606d6ee1aa65fcd3b51375a9ef6436e9c9280b0dd63c/dlib-19.15.0.tar.gz (3.3MB)
    100% |████████████████████████████████| 3.3MB 3.7MB/s 
Collecting facebook-sdk (from -r requirements.txt (line 15))
  Downloading https://files.pythonhosted.org/packages/34/ac/830c1f2821847bf191687ac57d3c8416623c7c496332cb281c949c05a308/facebook_sdk-3.0.0-py2-none-any.whl
Requirement already satisfied: urllib3 in /Library/Python/2.7/site-packages (from selenium->-r requirements.txt (line 2)) (1.23)
Requirement already satisfied: EasyProcess in /Library/Python/2.7/site-packages (from pyvirtualdisplay->-r requirements.txt (line 3)) (0.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/2.7/site-packages (from requests->-r requirements.txt (line 5)) (2018.8.13)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Python/2.7/site-packages (from requests->-r requirements.txt (line 5)) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /Library/Python/2.7/site-packages (from requests->-r requirements.txt (line 5)) (2.7)
Requirement already satisfied: Pillow in /Library/Python/2.7/site-packages (from face_recognition->-r requirements.txt (line 6)) (5.2.0)
Collecting face-recognition-models>=0.3.0 (from face_recognition->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/cf/3b/4fd8c534f6c0d1b80ce0973d01331525538045084c73c153ee6df20224cf/face_recognition_models-0.3.0.tar.gz (100.1MB)
    100% |████████████████████████████████| 100.2MB 7.3MB/s 
Collecting Click>=6.0 (from face_recognition->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 10.0MB/s 
Requirement already satisfied: pytz in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from django->-r requirements.txt (line 7)) (2013.7)
Requirement already satisfied: python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from matplotlib->-r requirements.txt (line 10)) (1.5)
Requirement already satisfied: tornado in /Library/Python/2.7/site-packages (from matplotlib->-r requirements.txt (line 10)) (5.1)
Requirement already satisfied: pyparsing>=1.5.6 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from matplotlib->-r requirements.txt (line 10)) (2.0.1)
Requirement already satisfied: nose in /Library/Python/2.7/site-packages (from matplotlib->-r requirements.txt (line 10)) (1.3.7)
Collecting PyWavelets>=0.4.0 (from scikit-image->-r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/da/2a/dd1b00eb1835e0f8d6f8b8f024fb77183cf1fe1d6910d95d48394cd80740/PyWavelets-0.5.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.8MB)
    100% |████████████████████████████████| 4.8MB 1.0MB/s 
Collecting cloudpickle>=0.2.1 (from scikit-image->-r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/e7/bf/60ae7ec1e8c6742d2abbb6819c39a48ee796793bcdb7e1d5e41a3e379ddd/cloudpickle-0.5.3-py2.py3-none-any.whl
Collecting networkx>=1.8 (from scikit-image->-r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/11/42/f951cc6838a4dff6ce57211c4d7f8444809ccbe2134179950301e5c4c83c/networkx-2.1.zip (1.6MB)
    100% |████████████████████████████████| 1.6MB 7.3MB/s 
Collecting dask[array]>=0.9.0 (from scikit-image->-r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/91/52/427541141707ac533a6dcafa3bff7ff8b57ded3c9ea84d6ec014d15fbbff/dask-0.18.2-py2.py3-none-any.whl (645kB)
    100% |████████████████████████████████| 655kB 7.9MB/s 
Collecting six>=1.10.0 (from scikit-image->-r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting traitlets>=4.2 (from ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl (74kB)
    100% |████████████████████████████████| 81kB 5.1MB/s 
Requirement already satisfied: setuptools>=18.5 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from ipython->-r requirements.txt (line 13)) (18.5)
Collecting simplegeneric>0.8 (from ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/3d/57/4d9c9e3ae9a255cd4e1106bb57e24056d3d0709fc01b2e3e345898e49d5b/simplegeneric-0.8.1.zip
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/7d/cd/1750d6c35fe86d35f8562091737907f234b78fdffab42b29c72b1dd861f4/backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting pygments (from ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |████████████████████████████████| 849kB 8.1MB/s 
Collecting appnope; sys_platform == "darwin" (from ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/87/a9/7985e6a53402f294c8f0e8eff3151a83f1fb901fa92909bb3ff29b4d22af/appnope-0.1.0-py2.py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 5.5MB/s 
Collecting pickleshare (from ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/9f/17/daa142fc9be6b76f26f24eeeb9a138940671490b91cb5587393f297c8317/pickleshare-0.7.4-py2.py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/d1/b0/1a6c262da35c779dd79550137aa7c298a424987240a28792ec5ccf48f848/prompt_toolkit-1.0.15-py2-none-any.whl (247kB)
    100% |████████████████████████████████| 256kB 7.4MB/s 
Collecting decorator (from ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Collecting pathlib2; python_version == "2.7" or python_version == "3.3" (from ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/66/a7/9f8d84f31728d78beade9b1271ccbfb290c41c1e4dc13dbd4997ad594dcd/pathlib2-2.3.2-py2.py3-none-any.whl
Requirement already satisfied: futures in /Library/Python/2.7/site-packages (from tornado->matplotlib->-r requirements.txt (line 10)) (3.2.0)
Requirement already satisfied: singledispatch in /Library/Python/2.7/site-packages (from tornado->matplotlib->-r requirements.txt (line 10)) (3.4.0.3)
Requirement already satisfied: backports_abc>=0.4 in /Library/Python/2.7/site-packages (from tornado->matplotlib->-r requirements.txt (line 10)) (0.5)
Collecting toolz>=0.7.3; extra == "array" (from dask[array]>=0.9.0->scikit-image->-r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/14/d0/a73c15bbeda3d2e7b381a36afb0d9cd770a9f4adc5d1532691013ba881db/toolz-0.9.0.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 4.3MB/s 
Collecting ipython-genutils (from traitlets>=4.2->ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting enum34; python_version == "2.7" (from traitlets>=4.2->ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython->-r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/16/2a/557af1181e6b4e30254d5a6163b18f5053791ca66e251e77ab08887e8fe3/scandir-1.9.0.tar.gz
pywavelets 0.5.2 has requirement numpy>=1.9.1, but you'll have numpy 1.8.0rc1 which is incompatible.
scikit-image 0.14.0 has requirement matplotlib>=2.0.0, but you'll have matplotlib 1.3.1 which is incompatible.
scikit-image 0.14.0 has requirement scipy>=0.17.0, but you'll have scipy 0.13.0b1 which is incompatible.
Installing collected packages: dlib, face-recognition-models, Click, face-recognition, django, PyWavelets, cloudpickle, decorator, networkx, toolz, dask, six, scikit-image, scikit-learn, ipython-genutils, enum34, traitlets, simplegeneric, backports.shutil-get-terminal-size, pygments, appnope, ptyprocess, pexpect, scandir, pathlib2, pickleshare, wcwidth, prompt-toolkit, ipython, facebook-sdk
  Running setup.py install for dlib ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-zy7TWd/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-AOyhPh/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    package init file 'dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 2.7.10 (default, Oct  6 2017, 22:29:07)
    Invoking CMake setup: 'cmake /private/tmp/pip-install-zy7TWd/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/tmp/pip-install-zy7TWd/dlib/build/lib.macosx-10.13-intel-2.7 -DPYTHON_EXECUTABLE=/usr/bin/python -DCMAKE_BUILD_TYPE=Release'
    -- The C compiler identification is unknown
    -- The CXX compiler identification is unknown
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- broken
    CMake Error at /Library/Python/2.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
      The C compiler
    
        "/usr/bin/cc"
    
      is not able to compile a simple test program.
    
      It fails with the following output:
    
        Change Dir: /tmp/pip-install-zy7TWd/dlib/build/temp.macosx-10.13-intel-2.7/CMakeFiles/CMakeTmp
    
        Run Build Command:"/usr/bin/make" "cmTC_d7522/fast"
        xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    
    
    
    
      CMake will not be able to correctly generate this project.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-zy7TWd/dlib/build/temp.macosx-10.13-intel-2.7/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-zy7TWd/dlib/build/temp.macosx-10.13-intel-2.7/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-zy7TWd/dlib/setup.py", line 257, in <module>
        'Topic :: Software Development',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/tmp/pip-install-zy7TWd/dlib/setup.py", line 133, in run
        self.build_extension(ext)
      File "/private/tmp/pip-install-zy7TWd/dlib/setup.py", line 170, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/private/tmp/pip-install-zy7TWd/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/tmp/pip-install-zy7TWd/dlib/build/lib.macosx-10.13-intel-2.7', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-zy7TWd/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-AOyhPh/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-zy7TWd/dlib/`

**Comment by Soutcast** [comment]
Fixed the second error first by installing xcode command utils:
`xcode-select --install`
Then by manually installing dlib. Instructions found here for anyone experiencing the same error:
https://gist.github.com/ageitgey/629d75c1baac34dfa5ca2a1928a7aeaf

**Comment by Green-Wolf** [comment]
Thanks for letting me know how you fixed the issues, i've updated the mac installation guide.
