### ISSUE TITLE
Error Filling out Facebook Profiles

### ISSUE THREAD

**Issue by jjfneto** [SpiderLabs/social_mapper#5]
[-] Error Filling out Facebook Profiles [-]
Message: Process unexpectedly closed with status 1

[-]

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:01.312353

**Comment by KhizarCodes** [comment]
`[-] Error Filling out Facebook Profiles [-]
[Errno 8] Exec format error
[-]


Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:00.244015`

Credentials for the account are correct. Still getting this error.

**Comment by SherlocKOficial** [comment]
[-] Error Filling out Facebook Profiles [-]
cmd=['Xvfb', '-help']
OSError=[Error 2] O sistema não pode encontrar o arquivo especificado
Program install error!
[-]


Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:00.014000

**Comment by ktsang236** [comment]
I got the error too when using -fb
C:\py_projects\social_mapper>python social_mapper.py -f imagefolder -i ./mytargets -m fast -fb
[-] Error Filling out Facebook Profiles [-]
cmd=['Xvfb', '-help']
OSError=[Error 2] The system cannot find the file specified
Program install error!
[-]


Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:00.014000
--=============
for instagram:

C:\py_projects\social_mapper>python social_mapper.py -f imagefolder -i ./mytargets -m fast -ig
Traceback (most recent call last):
  File "social_mapper.py", line 1128, in <module>
    peoplelist = fill_instagram(peoplelist)
  File "social_mapper.py", line 307, in fill_instagram
    InstagramfinderObject = instagramfinder.Instagramfinder(showbrowser)
  File "./modules\instagramfinder.py", line 15, in __init__
    display = Display(visible=0, size=(1600, 1024))
  File "C:\python27\lib\site-packages\pyvirtualdisplay\display.py", line 34, in
__init__
    self._obj = self.display_class(
  File "C:\python27\lib\site-packages\pyvirtualdisplay\display.py", line 52, in
display_class
    cls.check_installed()
  File "C:\python27\lib\site-packages\pyvirtualdisplay\xvfb.py", line 38, in che
ck_installed
    ubuntu_package=PACKAGE).check_installed()
  File "C:\python27\lib\site-packages\easyprocess\__init__.py", line 180, in che
ck_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Error 2] The system cannot find the file specified
Program install error!

Thanks a lot if anyone help!!

**Comment by Robyn12** [comment]
You guys could try installing xvfb binary from repos. I hope this works for you.

**Comment by Green-Wolf** [comment]
Could you guys try putting putting some debug statements into the code to find out where it is failing? There are all different error messages so are probably different issues.

**Comment by hungpham2411** [comment]
I get this error:
```
[-] Error Filling out Facebook Profiles [-]
'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
[-]
```
[geckodriver.log](https://github.com/SpiderLabs/social_mapper/files/2282169/geckodriver.log)

**Comment by jjfneto** [comment]
My error:
[-] Error Filling out Facebook Profiles [-]
Message: Process unexpectedly closed with status 1
[-]
Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html
Task Duration: 0:00:01.312353

[geckodriver.log](https://github.com/SpiderLabs/social_mapper/files/2284712/geckodriver.log)

**Comment by jjfneto** [comment]
@hungpham2411 @ktsang236 @SherlocKOficial @KhizarCodes 

I solved my problem!

I simply left the root and executed the normal command with my user, without entering the "sudo su" and without adding the "sudo" command in the front.

**Comment by hungpham2411** [comment]
@jjfneto 
I don't use the "sudo" when executing run command.

**Comment by lorenzoromani1983** [comment]
I am getting the same error when using Facebook. I'm on Kali Linux. Solutions?

**Comment by Green-Wolf** [comment]
Which error are you having @lorenzoromani1983, Is it the xvfb one? Try @Robyn12's solution?

**Comment by lorenzoromani1983** [comment]
I uninstalled xvfb and reinstalled it with sudo apt-get install xvfb.
it still crashes. It crawls some Facebook profiles (20-30), then stops.

**Comment by Green-Wolf** [comment]
Any error after those profiles @lorenzoromani1983?

**Comment by lorenzoromani1983** [comment]
no...nothing!

**Comment by lorenzoromani1983** [comment]
This is what i get:

Facebook Check 25/290 : gianluca valentini                                [-] Error Filling out Facebook Profiles [-]
''
[-]

(AND THEN THE REMAINING PROFILES ARE LISTED THIS WAY, BUT NOT CRAWLED)

flavia fontanelli
	Facebook: https://www.facebook.com/flavia.fontanelli.9?ref=br_rs

emilio anglani
	Facebook: https://www.facebook.com/emilio.anglani?ref=br_rs

andrea eliseo
	Facebook: https://www.facebook.com/profile.php?id=609712695&ref=br_rs

giacomo giugliano
	Facebook: https://www.facebook.com/giacomo.giugliano?ref=br_rs

**Comment by lorenzoromani1983** [comment]
i CHECKED the geckodriver.log file. it states the following:

JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3/yV/r/BHfrPrWxY38.js, line 4: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3/yV/r/BHfrPrWxY38.js, line 4: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3/yV/r/BHfrPrWxY38.js, line 4: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3/yV/r/BHfrPrWxY38.js, line 4: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Can't use WebGL in headless mode (https://bugzil.la/1375585).
JavaScript warning: https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yf/l/en_US/13B9xuqtsdV.js, line 26: Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Can't use WebGL in headless mode (https://bugzil.la/1375585).

**Comment by Green-Wolf** [comment]
Its strange i haven't come across this, however it seems to be a flaw with Firefox (https://bugzil.la/1375585) that we will just have to wait to be fixed. As a temporary workaround try using '-s' flag to show the browser, so it doesn't run in headless mode by default. Please let me know if the -s flag fixes it for you, good luck!

**Comment by lorenzoromani1983** [comment]
i have tried to run with -s but the browser doesn't show up :)

**Comment by Green-Wolf** [comment]
That probally points to a problem with your selenium/browser/geckodriver install then. Must still be not quite right.

**Comment by lorenzoromani1983** [comment]
Ithink i'll do it...

**Comment by Michealpool** [comment]
i am facing this error with python3. 

[-] Error Filling out Facebook Profiles [-]
startswith first arg must be bytes or a tuple of bytes, not str
[-]

**Comment by Green-Wolf** [comment]
python3 is not supported

**Comment by Zulan69** [comment]
Deben agregar a la carpeta /usr/bin el archivo de geckodriver....no more

**Comment by Green-Wolf** [comment]
Hi @perixiaowan , did you install then xcode toolset via the command line, thats usually the cause of this issue?

**Comment by coder-rishav** [comment]
> hello,
> I encount the same question, sincerely looking forward to your reply. My developing environment on Mac OSX. The Error info below.
> --- /git-code/social_mapper ‹master* M?› » python social_mapper.py -f imagefolder -i ./Input-Examples/imagefolder/ -m fast -fb 1 ↵
> 
> [-] Error Filling out Facebook Profiles [-]
> cmd=['Xvfb', '-help']
> OSError=[Errno 2] No such file or directory
> Program install error!
> [-]
> ## Results file: SM-Results/results-social-mapper.csv
> HTML file: SM-Results/results-social-mapper.html
> 
> I try several ways to install Xvfb on OSX operation. But I don't know how to install 'Xvfb'. need your help. thank you very much.

try :
apt-get install xvfb

**Comment by coder-rishav** [comment]
use : 
apt-get install xvfb

**Comment by Greenwolf** [comment]
On OSX you can install xquartz (x11), it's an app and you can right click it in your dock to launch shell, try running social mapper from there

**Comment by Deepi-cyber** [comment]
> python3 is not supported

assert sys.version_info >= (3,), "Only Python 3 is currently supported."
whats this then mentoned in the program social_mapper.py

**Comment by Greenwolf** [comment]
> > python3 is not supported
> 
> assert sys.version_info >= (3,), "Only Python 3 is currently supported."
> whats this then mentoned in the program social_mapper.py

When the tool was first released it was Python2. It has since been updated to use Python3.

**Comment by tewedaj** [comment]
[-] Error Filling out Facebook Profiles [-]
Message: Process unexpectedly closed with status 1

[-]


Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

**Comment by vdlame** [comment]
i have the same error , and i have xvfb installed , and a use python3 , any fix in 2021 ?

**Comment by vdlame** [comment]
[+] Facebook Login Page loaded successfully [+]
[-] Error Filling out Facebook Profiles [-]
Message: Element <button id="loginbutton" class="_42ft _4jy0 _52e0 _4jy6 _4jy1 selected _51sy" name="login" type="submit"> is not clickable at point (678,343) because another element <div class="_9o-f"> obscures it

this is just the facebook login page has change
Please can you make a new social_mapper version Greenwolf ?

**Comment by faccboy** [comment]
Same issue here. 

kali㉿kali)-[~/Downloads/social_mapper]
└─$ sudo python3 social_mapper.py -f imagefolder -i /home/kali/Downloads/social_mapper/Input-Examples/imagefolder/ -m fast -fb -s

[-] Error Filling out Facebook Profiles [-]
Message: Process unexpectedly closed with status 1

[-]


Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Task Duration: 0:00:00.123185

**Comment by Rajkumar-kumawat** [comment]
sudo python3 social_mapper.py  -f imagefolder -i /home/rajkumar/Desktop/s/social_mapper/Input-Examples/imagefolder/ -m fast -t loose -fb -ig -li                                                                   1 ⨯
[-] Error Filling out Facebook Profiles [-]
__init__() got an unexpected keyword argument 'options'
[-]
Traceback (most recent call last):
  File "/home/rajkumar/Desktop/s/social_mapper/social_mapper.py", line 1266, in <module>
    peoplelist = fill_instagram(peoplelist)
  File "/home/rajkumar/Desktop/s/social_mapper/social_mapper.py", line 410, in fill_instagram
    InstagramfinderObject = instagramfinder.Instagramfinder(showbrowser)
  File "/home/rajkumar/Desktop/s/social_mapper/modules/instagramfinder.py", line 30, in __init__
    self.driver = webdriver.Firefox(firefox_profile=firefoxprofile, options=opts)
TypeError: __init__() got an unexpected keyword argument 'options'
