### ISSUE TITLE
Can't add non-esr firefox

### ISSUE THREAD

**Issue by IanSteg** [SpiderLabs/social_mapper#62]
When I do the command
> sudo add-apt-repository ppa:mozillateam/firefox-next && sudo apt update && sudo apt upgrade

I get the following output [output](https://pastebin.com/q2J57jCw)
Using fresh install of Kali and have ran

> apt-get update && apt-get upgrade

**Comment by neez333** [comment]
Same exact issue here. Also on a fresh Kali install as well

**Comment by Green-Wolf** [comment]
This is a problem installing firefox on Kali, i'm not sure why you're having problems on a fresh install, as multiple people have it working. I would suggest asking the Kali/Mozilla team. I'm closing this as it's not a social mapper issue.

**Comment by IanSteg** [comment]
@neez333 
Managed to get it installed by following steps [here](https://linuxconfig.org/how-to-install-latest-firefox-browser-on-debian-9-stretch-linux).

**Comment by Green-Wolf** [comment]
Brilliant, thanks for sharing your fix! 👍
