### ISSUE TITLE
LinkedIn Timeout Error

### ISSUE THREAD

**Issue by Koploseus** [SpiderLabs/social_mapper#64]
Hello, 

I have put my credential in social_mapper.py, but i get this error with Linkedln:

LinkedIn Timeout Error, session has expired and attempts to reestablish have failed

**Comment by Green-Wolf** [comment]
This is usually an issue with your internet connection not loading pages fast enough

**Comment by Koploseus** [comment]
Mmm weird, because it works with facebook, google + etc and i have the fiber.

**Comment by Green-Wolf** [comment]
That is odd 🤔

**Comment by Green-Wolf** [comment]
Just checked and linkedin code is still working.
