### ISSUE TITLE
error "No module named facebook"

### ISSUE THREAD

**Issue by gboxx12** [SpiderLabs/social_mapper#68]
![issue](https://user-images.githubusercontent.com/42805844/44786685-93a3c980-ab9d-11e8-9ddb-86a67e6f52d6.png)

Hi,
I'm trying to use social mapper for the first time. I'm trying to lunch it on Kali Linux.
Installed all the prerequisites, configured social network usernames & passwords in the config file.
But for some reason im getting an error (attached). Please help, what went wrong there? :)

Thanks!

**Comment by Green-Wolf** [comment]
Try having a look back at the old issues for solutions to this, i think it was a solved by installing facebook-sdk with pip but there were a few other solutions too.

**Comment by Green-Wolf** [comment]
I dont think your pip install requirements.txt has worked because thats another item in there that you're missing. Just keep troubleshooting and installing the required modules, you can do it!
