### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by joao32** [SpiderLabs/social_mapper#69]
HTTPSConnectionPool(host='www.facebook.com', port=443): Max retries exceeded with url: /search/async/profile_picture/?fbid=100008453387361&width=8000&height=8000 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbd99b23510>: Failed to establish a new connection: [Errno 113] No route to host',)))

Hi, 
I got this error above. I think that it is related with local network proxy. There is one way to set proxy  in the configuration file?

**Comment by Green-Wolf** [comment]
Hi @joao32 , I think to do this you would need to add some proxy code when the selenium browser instance is created. You would need to do this in each sites module file in the module folder. Alternatively you could try and and set the proxy for the system and see if that works:
https://www.shellhacks.com/linux-proxy-server-settings-set-proxy-command-line/

`$ export http_proxy="http://PROXY_SERVER:PORT"
$ export https_proxy="https://PROXY_SERVER:PORT"`
