### ISSUE TITLE
No module named modules?

### ISSUE THREAD

**Issue by Roulette10** [SpiderLabs/social_mapper#7]
Traceback (most recent call last):
  File "social_mapper.py", line 1, in <module>
    from modules import facebookfinder
ImportError: No module named modules

**Comment by hpiedcoq** [comment]
same here

**Comment by Roulette10** [comment]
nevermind this has already been answered. Delete all the lines with modules in them and replace it with

import sys
sys.path.insert(0, './modules')
import facebookfinder
import twitterfinder
import instagramfinder
import linkedinfinder
import vkontaktefinder
import weibofinder
import doubanfinder
import googleplusfinder
