### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by flawSec** [SpiderLabs/social_mapper#71]
[+] Facebook Login Page loaded successfully [+]
[+] Facebook Login Success [+]

Facebook Check 1/4 : Debora Fashoro                                Illegal instruction

**Comment by Green-Wolf** [comment]
What OS are you running on?

**Comment by flawSec** [comment]
Kali Linux

**Comment by Green-Wolf** [comment]
Thats strange, lots of people have been using it on kali without issues. Try running with the -vv flag for verbose mode or adding/uncommenting some of the error reporting statements in the facebook modules to help debug it

**Comment by animages** [comment]
I'm getting the same error
https://cdn.discordapp.com/attachments/355791032748867586/546126598223429647/unknown.png

**Comment by animages** [comment]
"It means the CPU attempted to execute an instruction it didn't understand. This could be caused by corruption I guess, or maybe it's been compiled for the wrong architecture (in which case I would have thought the O/S would refuse to run the executable)."
And this is what I read somewhere.

**Comment by Green-Wolf** [comment]
Hi @animages, I'm not sure what causes this issue, but its verified as working on Kali Linux so i would running it there.
