### ISSUE TITLE
Missing prerequisites for building `dlib`, when installing from requirements.txt

### ISSUE THREAD

**Issue by rizdaprasetya** [SpiderLabs/social_mapper#72]
When trying to install requirements by running: 
`python -m pip install --no-cache-dir -r requirements.txt`

Some linux distros will encounter the following when pip is installing `dlib` :
```
CMake must be installed to build the following extensions: dlib
```
![screen shot 2018-09-06 at 4 17 11 pm](https://user-images.githubusercontent.com/13027142/45148185-e3634000-b1f0-11e8-871f-114e8521cbc2.png)
like some of these people:
- https://github.com/SpiderLabs/social_mapper/issues/61
- https://github.com/SpiderLabs/social_mapper/issues/60

This is because DLIB require some prerequisites (cmake, libgtk-3-dev, libboost-all-dev).
On Ubuntu / Debian alike, this can be solved by installing:
```
sudo apt-get install build-essential cmake
sudo apt-get install libgtk-3-dev
sudo apt-get install libboost-all-dev
```
For other OS try following these useful blog post:
https://www.pyimagesearch.com/2017/03/27/how-to-install-dlib/

Might worth to add those as additional `prerequisites`.
Or just make this issue as reference when people encounter it.

Thanks. 
Awesome works on the `social_mapper`!

**Comment by Green-Wolf** [comment]
Brilliant, thanks very much, i've updated the readme!
