### ISSUE TITLE
Social mapper doesn't work in VK

### ISSUE THREAD

**Issue by artasoftware** [SpiderLabs/social_mapper#74]
Whatever I try to find I always get this error from vk:

```
[+] VKontakte Login Page loaded successfully [+]
Traceback (most recent call last):
  File "social_mapper.py", line 1133, in <module>
    peoplelist = fill_vkontakte(peoplelist)
  File "social_mapper.py", line 547, in fill_vkontakte
    VkontaktefinderObject.doLogin(vk_username,vk_password)
  File "/opt/social_mapper/modules/vkontaktefinder.py", line 38, in doLogin
    if(str(self.driver.title).encode('ascii','replace').startswith("Log in") == False):
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```
How can I fix it? 

Thanks.

**Comment by Green-Wolf** [comment]
If you visit the vk url from the module in firefox can you take a screenshot of the title of a successful login and a failed login? It could be a regional issue where the url title isn't in ascii. I just checked and its fine on my end

**Comment by artasoftware** [comment]
What module in firefox do you mean?

**Comment by Green-Wolf** [comment]
Ah i mean if you open ./modules/vkontaktefinder.py and pull out the url for vk.com for the login page. Then browse to it in firefox and take the screenshots so I can have a look at the title?

**Comment by artasoftware** [comment]
![vk](https://user-images.githubusercontent.com/22652036/45739336-6924b980-bbfb-11e8-9a7c-694cc56089ef.JPG)
`<title>Log in | VK</title>`

**Comment by artasoftware** [comment]
Fix:
if(self.driver.title.encode('ascii','replace').startswith("Log in") == False):
- without str. Error happens because my account name is not it ascii (another language).

**Comment by Green-Wolf** [comment]
oh nice thanks for sharing your fix! Would you like to edit it for each modules file? Then submit a pull request and i'll add you to contributors?

**Comment by Green-Wolf** [comment]
Fixed across all modules for logins
