### ISSUE TITLE
/del

### ISSUE THREAD

**Issue by e13267212** [SpiderLabs/social_mapper#79]
/del

**Comment by Green-Wolf** [comment]
I'm glad you solved your issue 😄

**Comment by e13267212** [comment]
> Help me please, i have an problem at the last step:
> 
> Please provide Facebook Login Credentials in the social_mapper.py file
> Traceback (most recent call last):
> File "social_mapper.py", line 1133, in 
> peoplelist = fill_vkontakte(peoplelist)
> File "social_mapper.py", line 546, in fill_vkontakte
> VkontaktefinderObject = vkontaktefinder.Vkontaktefinder(showbrowser)
> File "/home/e13267212/Загрузки/social_mapper-master/modules/vkontaktefinder.py", line 16, in **init**
> display = Display(visible=0, size=(1600, 1024))
> File "/home/e13267212/.local/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 34, in **init**
> self._obj = self.display_class(
> File "/home/e13267212/.local/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 52, in display_class
> cls.check_installed()
> File "/home/e13267212/.local/lib/python2.7/site-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
> ubuntu_package=PACKAGE).check_installed()
> File "/home/e13267212/.local/lib/python2.7/site-packages/easyprocess/**init**.py", line 180, in check_installed
> raise EasyProcessCheckInstalledError(self)
> easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
> OSError=[Errno 2] No such file or directory
> Program install error!
> You can install it in terminal:
> sudo apt-get install xvfb



> I'm glad you solved your issue 😄

Can u help me with other issue?

**Comment by e13267212** [comment]
(Sorry for my English)
When i type 
"python social_mapper.py -f imagefolder -i ./Input-Examples/imagefolder -m fast -vk" 

i have an error like:
[+] VKontakte Login Page loaded successfully [+]
Traceback (most recent call last):
File "social_mapper.py", line 1133, in <module>
peoplelist = fill_vkontakte(peoplelist)
File "social_mapper.py", line 547, in fill_vkontakte
VkontaktefinderObject.doLogin(vk_username,vk_password)
File "/home/e13267212/Загрузки/social_mapper-master/modules/vkontaktefinder.py", line 38, in doLogin
if(str(self.driver.title).encode('ascii','replace').startswith("Log in") == False):
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

**Comment by Green-Wolf** [comment]
Hey @e13267212, Is your VK account name in a non ascii language? I changed the code about 5 minutes ago so try with the new version. Someone else had this issue last week. 
Basically remove the str() so the line becomes:
if(self.driver.title.encode('ascii','replace').startswith("Log in") == False):
& for the other line in the file with the same kind of thing 😄

**Comment by e13267212** [comment]
> Hey @e13267212, Is your VK account name in a non ascii language? I changed the code about 5 minutes ago so try with the new version. Someone else had this issue last week.
> Basically remove the str() so the line becomes:
> if(self.driver.title.encode('ascii','replace').startswith("Log in") == False):
> & for the other line in the file with the same kind of thing smile

Fixed, love u <3 I create new topic with other problem, check it please
