### ISSUE TITLE
logo proposal for Social_mapper

### ISSUE THREAD

**Issue by candyskull920** [SpiderLabs/social_mapper#81]
Hello
I am an open source enthusiast and I am looking to expand my work portfolio.
I would like to collaborate with your project I can provide a logo for your application.

Good day
Skull C.

**Comment by Green-Wolf** [comment]
Hi @candyskull920 , what did you have in mind 😄 ?

**Comment by candyskull920** [comment]
The sooner I'll get my proposals.

Good day
Skull C.

**Comment by candyskull920** [comment]
Hi @Green-Wolf  this is my proposal I can make any modification that you want either color or design.
!
![looo-ersion-1](https://user-images.githubusercontent.com/43797200/46567003-c0af6e80-c8f7-11e8-82a1-28e1a70ee2e0.jpg)
![logo-version-1](https://user-images.githubusercontent.com/43797200/46566974-1f281d00-c8f7-11e8-837e-ec5b1206bff5.jpg)
![logo-version-3](https://user-images.githubusercontent.com/43797200/46566975-20594a00-c8f7-11e8-9250-fd31bcdafe92.jpg)
![logo-version-4 1](https://user-images.githubusercontent.com/43797200/46566976-20f1e080-c8f7-11e8-911d-a6bd0a7d0445.jpg)

**Comment by Green-Wolf** [comment]
Hi @candyskull920, thanks very much! Could you do the top one (target, multiple people) again in the green?

Also thank you very much for sharing these, where were you hoping I would put them? Is there an icon slot on github?

**Comment by candyskull920** [comment]
Hi @green-wolf I would like the logo to appear in the readme I can do the pull request to add it after I change the color from blue to green

**Comment by Green-Wolf** [comment]
Sure, please make it smaller though, like thumbnail size

**Comment by candyskull920** [comment]
Hi @Green-Wolf 
I am already finishing the modifications of the proposal, I would like to know what type of license they use for your project?

Good day
Skull C.

**Comment by Green-Wolf** [comment]
Hi @candyskull920, Social Mapper uses a GNU General Public, so it is free for reuse.

**Comment by candyskull920** [comment]
Hi @Green-Wolf 
Here is my proposal with the modification you requested.
When I want I can do the pull requests to add it to the readme.
![audifnos-3](https://user-images.githubusercontent.com/43797200/46686869-6f3d0300-cbc7-11e8-93cf-bdc0fc4a0d89.png)
![logo-version-5](https://user-images.githubusercontent.com/43797200/46686871-6fd59980-cbc7-11e8-88ae-d51dfde742e6.jpg)

**Comment by Green-Wolf** [comment]
Looks great, go for it!

**Comment by Green-Wolf** [comment]
Apologies Candy Skull, I'm not comfortable accepting links to external resources or receiving files for the project. I wish you luck with your designing.

**Comment by candyskull920** [comment]
Hi @green-wolf
good day, I thought that the design had been to your liking, if you want I can modify the proposal to a more according to your taste or that you consider more attractive
