### ISSUE TITLE
Not able to find Profile 

### ISSUE THREAD

**Issue by bearhunt11** [SpiderLabs/social_mapper#85]
When trying to run social_mapper i ran into the following error:

Error Filling out Facebook Profiles [-]
Message: Can't load the profile. Profile Dir: /tmp/tmp05FD68 If you specified a log_file in the FirefoxBinary constructor, check it for details.

Never mind. I had to upgrade selenium 3.14.

**Comment by bearhunt11** [comment]
Never mind. I had to upgrade selenium 3.14

uninstall selenium 2.53 and install to selenium 3.14

**Comment by macmakran** [comment]
hlw hii

**Comment by macmakran** [comment]
hlw hii

**Comment by macmakran** [comment]
hlw
