### ISSUE TITLE
Fetching less pages than total result number

### ISSUE THREAD

**Issue by orblatt** [SpiderLabs/social_mapper#90]
I ran the script with all the needed credentials, and got back the results for querying a specific company using -cid flag. It seems that the script identified hundreds of entities that belong to the company, but when i check the results, there were only 14 results in the csv file.

LOG:
Using supplied company Id: <REDACTED>
[*] Using company ID: <REDACTED>
[*] 850 Results Found
[*] Fetching 21 Pages

[*] Fetching page 20/21 with 40 results for <REDACTED>

Why not all the employees that were found had their own record in the csv?

**Comment by Green-Wolf** [comment]
Theres a number of reasons this can happen, sometimes the employees don't have a picture. Sometimes the employees wont show the picture unless your a 3rd degree contact. 

Could try connecting with some company members to get some connection degrees before re running.
