### ISSUE TITLE
Many duplicates when using -f company

### ISSUE THREAD

**Issue by willothewasp** [SpiderLabs/social_mapper#92]
After using:
`python2 social_mapper.py -f company -i "<company_name>" -m fast -li`
the created files contain multiple duplicates, and some profiles appear as many as four times with the same data.

**Comment by Green-Wolf** [comment]
Thats very strange, i've never had that occour before. Would you be willing to share the input company + generated output so I can have a look at it further?

**Comment by Green-Wolf** [comment]
Closing due to no follow up.
