### ISSUE TITLE
No result if image file named randomly

### ISSUE THREAD

**Issue by rickytik** [SpiderLabs/social_mapper#95]
Hi 
Installed your code, everything was OK 
Tried to find a target in VK by using an image file which was named randomly (digits and letters) and code returned no result. After renaming it to name and surname of a target (for ex. peter smith.jpg) code gave result. 
Is it possible to make a search without naming files? Sometimes targets may have their pages named randomly (for ex: peter, peter.s., just Smith, Smith P, Tough P.S., etc)

And second question: is it possible to return not just one result. For ex, 5 results from the highest to the lowest possible option?

**Comment by Green-Wolf** [comment]
Hi @rickytik ,

1) Unfortunately not. It relies on narrowing the search space with the name search, then downloads the results and does facial recognition to compare them and find a match. To do what you're asking for would require all of the possible results in a database, which is beyond the scope for this tool.

2) This would be possible, but not with the current version of the tool. If you needed this functionality I would suggest making a fork and then you would have to heavily edit the code in social_mapper.py to keep the 5 most likely results. 

Hope this answered your questions!

**Comment by rickytik** [comment]
Thanks. I will try with fork.
I should work with 'distance' in functions. Am i right?

**Comment by Green-Wolf** [comment]
It returns a list of profiles, then depending if you run in fast or accurate mode when one is above the threshold it returns it as the final result (fast), on accurate it loops through and finds the highest (most accurate) result. 

What you would want to do is replace this logic with logic that adds the first 5 matches or the top 5 matches to a list. You could make a new global list variables like facebook_list, linkedin_list,. then you would need to change how to HTML reports are generated from these. 

Let me know if you have any other questions 😄

**Comment by rickytik** [comment]
That is full answer. thx :-) i was going to write second variant
I have one more  question... just for  better getting it.. does it compare 'distances' with every fotos in profile while it loops through ? or just with one main photo?

**Comment by Green-Wolf** [comment]
It compares the distance in from the picture in the profile it finds with the name(like 15-20) to the threshold with the original picture

**Comment by Green-Wolf** [comment]
So simplified it's like:

```
Load original_picture
for picture in profile list
  is picture matched with original_picture number above 0.6 (standard)
    match found
  else
    pass
```

**Comment by Green-Wolf** [comment]
Oh sorry i misunderstood the question, it just does the main profile picture.

**Comment by Green-Wolf** [comment]
Looping through all public pictures would be a cool addition, very very slow but a bit more accurate 🤔
