### ISSUE TITLE
Login cookie unavailable

### ISSUE THREAD

**Issue by e-Euler** [SpiderLabs/social_mapper#96]
The Initial load of a linkedin login page does not create a cookie named li_at. This cookie is only available after a successful login.

**Comment by Green-Wolf** [comment]
Hello, could you share more details about this issue? Is it preventing the linkedin login? Does it cause a crash? if so can you post output please?

**Comment by e-Euler** [comment]
Created my own fork and did a clean install and everything works I don't know what had happened with the previous install. I do apologize.
