### ISSUE TITLE
Unable to install it on Windows x86

### ISSUE THREAD

**Issue by harimittapalli** [SpiderLabs/social_mapper#99]
Hi,

I tried to install it on Windows x86 system but getting below error.

Python version is 3.6
```
 -- Building for: NMake Makefiles
    CMake Error in CMakeLists.txt:
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.
```
Could you help us in getting this installed on my windows system.

**Comment by Green-Wolf** [comment]
Hi @harimittapalli ! Sorry but Windows is unsupported. Please try with Kali or Ubuntu.
